# Hand hardness density parametrization parameteris according to Geldsetzer & Jamieson (2000)
# https://arc.lib.montana.edu/snow-science/objects/issw-2000-121-127.pdf
DENSITY_PARAMETERS = {
    'PP': (45, 36),
    'PPgp': (83, 37),
    'DF': (65, 36),
    'RG': (154, 1.51),
    'RGmx': (91, 42),
    'FC': (112, 46),
    'FCmx': (56, 64),
    'DH': (185, 25),
    'MFCr': (292.25, 0),
}

# Map SnowPilot grain type to those we know
GRAIN_TYPE = {
    '': '!skip',
    'DF': 'DF',
    'DFbk': 'DF',
    'DFdc': 'DF',
    'DH': 'DH',
    'DHch': 'DH',
    'DHcp': 'DH',
    'DHla': 'DH',
    'DHpr': 'DH',
    'DHxr': 'DH',
    'FC': 'FC',
    'FCsf': 'FCmx',
    'FCso': 'FCmx',
    'FCxr': 'FCmx',
    'IF': 'MFCr',
    'IFbi': 'MFCr',
    'IFic': 'MFCr',
    'IFil': 'MFCr',
    'IFrc': 'MFCr',
    'IFsc': 'MFCr',
    'MF': 'MFCr',
    'MFcl': 'MFCr',
    'MFcr': 'MFCr',
    'MFpc': 'MFCr',
    'MFsl': 'MFCr',
    'PP': 'PP',
    'PPco': 'PP',
    'PPgp': 'PPgp',
    'PPhl': 'PP',
    'PPip': 'PP',
    'PPir': 'PP',
    'PPnd': 'PP',
    'PPpl': 'PP',
    'PPrm': 'PP',
    'PPsd': 'PP',
    'RG': 'RG',
    'RGlr': 'RGmx',
    'RGsr': 'RGmx',
    'RGwp': 'RGmx',
    'RGxf': 'RGmx',
    'SH': '!skip',
    'SHcv': '!skip',
    'SHsu': '!skip',
    'SHxr': '!skip',
}

# Translate hand hardness to numerical values
HAND_HARDNESS = {
    '': '!skip',
    'F-': 0.5,
    'F': 1,
    'F+': 1.5,
    '4F-': 1.5,
    '4F': 2,
    '4F+': 2.5,
    '1F-': 2.5,
    '1F': 3,
    '1F+': 3.5,
    'P-': 3.5,
    'P': 4,
    'P+': 4.5,
    'K-': 4.5,
    'K': 5,
    'K+': 5.5,
    'I-': 6,
    'I': 6,
    'I+': 6,
}
